### ISSUE TITLE
troubles to remove objects from collections

### ISSUE THREAD

**Issue by yannicksuter** [vznet/mongo-jackson-mapper#11]
I'm chasing a severe bug in our application and after some digging I somehow broke it down to this example. Using the jackson collection, I'm not able to remove documents. usualy it works for a single document which I just inserted. In the following example I just try to purge a unittest-collection.

``` java
import java.net.UnknownHostException;

import net.vz.mongodb.jackson.DBCursor;
import net.vz.mongodb.jackson.JacksonDBCollection;

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import com.mongodb.MongoException;
import com.orion.model.Account;

public class MongoTest {
    public static void main(String[] args) {

        try {
            Mongo mongo = new Mongo("localhost", 27017);
            DB db = mongo.getDB("orion-unittest");

            // get a single collection
            DBCollection collection = db.getCollection("account");

            // doesn't work
            JacksonDBCollection<Account, String> jacksonCollection = JacksonDBCollection.wrap(collection, Account.class, String.class);
            DBCursor<Account> jacksonCursor = jacksonCollection.find();
            while (jacksonCursor.hasNext()) {
                jacksonCollection.remove(jacksonCursor.next());
            }
            System.out.println(jacksonCollection.getCount());

            // works!
            com.mongodb.DBCursor cursor = collection.find();
            while (cursor.hasNext()) {
                collection.remove(cursor.next());
            }
            System.out.println(collection.getCount());

        } catch (UnknownHostException e) {
            e.printStackTrace();
        } catch (MongoException e) {
            e.printStackTrace();
        }

    }
}
```

Console output:
6
0

The strange part ist, when I monitor the mongo server I see the delete commands being passed. do I miss something, or is this a bug of the jackson mapper?

**Comment by jroper** [comment]
Are you able to post the source code for the account class?

What I suspect is that the account class is being deserialised slightly differently to the way it's being serialised.

Note that the argument you pass to jacksonCollection.remove() should be a query, not an object.  If you do pass in an object, then it has to match _exactly_.  This can cause issues for example if you have fields that use primitive types of fields with null values, because a primitive type can't have a null value.  There are many other edge cases as well.  I suspect you are running into one of these.

So, if you what you are intending to say is "delete an object that has all of the exact same properties as this one I pass in", then you might need to modify your mappings a bit so that what is deserialised from MongoDB matches exactly what is serialised.  If on the other hand you just want to remove a single object with a particular id (as in the above code), then jacksonCollection.removeById(jacksonCursor.next().getId()) is probably what you're looking for, and will also perform better, because MongoDB doesn't have to load and match every property of your document before deleting it.

**Comment by yannicksuter** [comment]
sure, just updated my question

On Mon, Apr 2, 2012 at 4:40 PM, James Roper
reply@reply.github.com
wrote:

**Comment by yannicksuter** [comment]
thanks for your reply, here the Account class - very simple construct until now.

```
import net.vz.mongodb.jackson.Id;

public class Account {
    @Id
    String id;
    String nickname = null;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}
```

**Comment by yannicksuter** [comment]
ok, good point about the serialization, but thats why I constructed this example. as I use a cursor I thought not being responsible for the correctness of the objects themself. thanks for the explanations - the usage of deleting byID just solved my problem.

**Comment by jroper** [comment]
I'll do some tests, but the most likely cause is that there are some documents that have ids of type ObjectId.  The following code will always fail:

```
jacksonCollection.drop(); // drops the collection to ensure it's empty
jacksonCollection.save(new Account());
jacksonCollection.remove(jacksonCollection.findOne());
assertEquals(0, jacksonCollection.getCount());
```

The reason for this, is that MongoDB, when you don't specify an id property, generates one for you to be of type ObjectId.  So the result of the save will be that there is an object in the collection that looks like this:

```
{"_id": ObjectId("4f7551a74206b4f8e692bda3")}
```

The Jackson mapper, as a convenience, automatically deserialises ObjectIds to Strings.  So the result of findOne() will be that you have an Account object with ID "4f7551a74206b4f8e692bda3".  However there is no way for Jackson to know when it serialises the Account object back to BSON that that string should be serialised as an ObjectId, so the remove statement ends up being equivalent to this on the mongo command line:

db.collection.remove({"_id": "4f7551a74206b4f8e692bda3"})

The issue is that  ObjectId("4f7551a74206b4f8e692bda3") is not equal to "4f7551a74206b4f8e692bda3", and hence nothing is deleted.

To check if this is what is happening, when you encounter this issue, do a db.find() on the command line, and see whether there are any ObjectId properties.

The simplest solution to this issue is to annotate your id property with @net.vz.mongdb.jackson.ObjectId, this will tell the Mongo Jackson Mapper to serialise it as an ObjectId.  Another solution is to change the type of the property to org.bson.types.ObjectId.  The latter makes things conceptually simpler, because there is no confusion as to what type the id is, but the former might be easier to work with since Strings are easier to pass around than ObjectIds.

**Comment by jroper** [comment]
I missed your last comment there, if deleteById solved the problem, then it's got nothing to do with ObjectId types.

**Comment by jroper** [comment]
As a side note, when I first wrote the library I thought having remove() and other things that accepted queries accept strongly typed objects was a good idea, but I'm now of the opinion that it creates more confusion than it's worth, so I'm actually deprecating those methods, in favour for using the _ById methods, and DBQuery._ built queries.

**Comment by yannicksuter** [comment]
Again, thanks for your help understanding the real problem. I changed again parts of my DOAs, I'm using now the @net.vz.mongdb.jackson.ObjectId annotation. Keep up the good work!
