### ISSUE TITLE
Upgrade to Jackson 2

### ISSUE THREAD

**Issue by benmccann** [vznet/mongo-jackson-mapper#12]
I'd love to see Jackson 2 supported by mongo-jackson-mapper!  It's largely just a package rename of the Jackson imports.

**Comment by jroper** [comment]
Hi Ben, work has already started on this, see the jackson-2 branch.  If you need something that works today, that branch currently works with Jackson 2, almost all tests pass, the only thing that doesn't work is Jackson view support, because Jackson 2 completely changes the way views are configured.  If you're not using Jackson views, then this branch will work fine for you.

However, there's a lot more work that I'd like to do on the Mongo Jackson Mapper before releasing a 2.0.  There are a number of features that I managed to get into Jackson 2 specifically for the Mongo Jackson Mapper, these are centered around automatically serialising values passed to queries and DBUpdates based on the serialisation config defined on the POJO.  If you define a custom serialiser on a property, for example, using the @ObjectId annotation, currently you need to manually serialise that property when using it in a query (ie, DBQuery.is("someProperty", new ObjectId(somevalue))).  I'd really like the 2.0 release to include this feature to automatically do that, but it will take a little longer for me to finish implementing it.

**Comment by benmccann** [comment]
Wow, awesome.  I just finished downgrading my project back to Jackson 1 and that's working pretty well for me, but I'll be sure to test out the new version when it's released!

**Comment by benmccann** [comment]
FYI, Jerkson just added Jackson 2 support, so I may try to upgrade Play after the next Jerkson release.  https://github.com/codahale/jerkson/commit/9b874e5bcbbff48f152328fcb256505d31309ad7

**Comment by benmccann** [comment]
Google HTTP Client just added Jackson 2 support as well (http://code.google.com/p/google-http-java-client/source/detail?r=f69a82238e663589ea31ddd8d2959099244ada22), so this is the only library I still use that hasn't upgraded yet.  I'd really love to get any Jackson 2 release out at all so that I can get rid of my Jackson 1 dependency.

**Comment by juanformoso** [comment]
benmccann, in the meantime, I downloaded the source code, built and deployed the "jackson-2" branch to our local repository, and migrated my project to use jackson 2 with that dependency. 

As long as you don't use views, it works.

**Comment by benmccann** [comment]
Hi Juan, I submitted a pull request for views support, but am still waiting for it to be committed: https://github.com/vznet/mongo-jackson-mapper/pull/24

**Comment by mdnorman** [comment]
I'd really like to see this upgrade as well. There are a number of other libraries that have upgraded, so I'm not able to use this library with any projects using those libraries.

**Comment by SebastianVomMeer** [comment]
Is anyone still working on this?

**Comment by benson-basis** [comment]
Hmm, @jroper, how about that pull request. Others, should we all center on some other repo and collaborate to go forward?

**Comment by juanformoso** [comment]
I'd love to see this go forward, so it has my vote to switch repos and/or ownership... although I have no idea if it's ethical, or even possible according to the license.

**Comment by SebastianVomMeer** [comment]
Apache 2 License, no need to worry about this. However, it would be nice to get some feedback of the original author before doing this step...

**Comment by jroper** [comment]
See http://mongojack.org.
