### ISSUE TITLE
Dates stored as int64 rather than UTC Datetime

### ISSUE THREAD

**Issue by jmcmillan** [vznet/mongo-jackson-mapper#2]
Hello

This is a really great library, I only have one issue with it so far:
Dates are stored as int64 (BSON type 0x12) rather than UTC Datetime (BSON type 0x09).
This seems to be that because standard JSON doesn't have a concept of dates, Jackson automatically converts dates into their millisecond timestamps (or a date string if configured).

It looks like the code for reading BSON is in the bson4jackson project, so that would probably need to fix the same issue first. The general idea of the fix, from what I can guess, would involve adding date read/write support to the BSON parsers and generators, and then writing serializers/deserializers that use the date read/write support, and then integrating these serializers/deserializers and have them somehow work by default.

If anyone can figure out a temporary workaround or easier solution that would be great :P

James

**Comment by jroper** [comment]
Hi James,

I'm glad you like the library.  I was expecting this to come up sooner or later, simply because I knew that BSON did something special with dates and I hadn't made any attempt to address it yet.  Currently serialisation is not done by bson4jackson, but rather by the jackson mapper itself, serialising to DBObjects (see net.vz.mongodb.jackson.internal.object.BsonObjectGenerator).  It's a busy time of year so I don't know when I will get to fixing this issue, but I will make sure it is the next thing I do and include it in the 1.2 release, which is almost ready.  If you want to have a go at fixing it yourself I'll be happy to accept any pull requests as long as there are unit tests.

Cheers,

James

**Comment by jroper** [comment]
Also there are currently 2 different deserialisers, one is bson4jackson and the other deserialises DBObjects.  I'm surprised that deserialisation doesn't just work... but I'll have to check it out.  A potential work around for now would be to implement a custom deserialiser and either annotate the field @JsonDeserialiser or supply a custom ObjectMapper to JacksonDBCollection (read the javadoc, make sure you add the JacksonMongoModule to your ObjectMapper).  I think though fixing this in the mapper would be less effort.

**Comment by jroper** [comment]
I've implemented this. I'm supposed to be off work sick today, but what else am I going to do at home when I'm sick? :)  A 1.2 release is on it's way, should be synced to maven central in a few hours.
