### ISSUE TITLE
Bad method overloading in DBQuery can result in faulty query objects

### ISSUE THREAD

**Issue by pmaedel** [vznet/mongo-jackson-mapper#4]
In DBQuery, a couple of methods are implemented as overloading methods, requiring either varargs (Object...) or a Collection as parameter. Due to precedence in JVM, each call to these methods with a Collection as a parameter will end up in the varargs method and finally result in a faulty query (object).

Example:
```List<String> stringList = new ArrayList<String>();
stringList.add("s1");
stringList.add("s2");
col.find(DBQuery.in("stringList", stringList)); //Ends up here:  in(String field, Object... values)

``````
Query Object generated:
```{stringList : { $in : [ [s1, s2] ] } }
``````

**Comment by jroper** [comment]
Thanks for reporting this.  I believe the reason why it is not resolving the collection method is because I've set the parameter type of the collection to be Object, whereas it should be a wildcard (Collection<?>).  If you were to change the list above to be List&lt;Object&gt;, I think you'll find it works as expected.  I've changed the method signature to accept Collection<?> for all methods on DBQuery that accept collections, and will release a new version soon.
