### ISSUE TITLE
Add support for org.codehaus.jackson.map.DeserializationConfig.Feature

### ISSUE THREAD

**Issue by criedel** [vznet/mongo-jackson-mapper#8]
There's already an enum JacksonDBCollection.Feature that seems to be the equivalent for jackson-mapper's org.codehaus.jackson.map.DeserializationConfig.Feature.
From time to time I get this error from jackson that there are unmapped fields in my collection after I changed my java entities.
It would be nice if the Feature FAIL_ON_UNKNOWN_PROPERTIES could be implemented and enabled by default in mongo-jackson-mapper. (the other FAIL_\* features might be nice too)

Thanks!

**Comment by jroper** [comment]
I agree that false is a good default for FAIL_ON_UNKNOWN_PROPERTIES.  Currently you can use custom object mapper configuration by passing in your own object mapper to JacksonDBCollection.wrap().  There are a few issues here that I haven't yet worked out a good way to fix:
- If you pass in your own object mapper, JacksonDBCollection makes no effort to set the config up that it needs, rather, you have to manually call ObjectMapper.registerModule(MongoJacksonMapperModule.INSTANCE).  The reason for this is that I don't think that JacksonDBCollection can assume that it can reconfigure an ObjectMapper passed to it, in particular, what if this object mapper has already been passed to it?  It would be adding its serializers/deserializers twice.
- The singleton ObjectMapper exists for convenience, so that proper caching is done if JacksonDBCollection.wrap is called many times.  Because it is singleton, reconfiguring it would have undesirable effects.  So it is intentional that JacksonDBCollection exposes no method for reconfiguring the ObjectMapper.

Possibly a better way to manage it while still providing convenience is to have a JacksonDBCollection builder (or factory), that used an ObjectMapper per instance of JacksonDBCollection, and documented this clearly and hence the need for the application to manage its own shared instances of JacksonDBCollection, if the application wants to take advantage of caching at the ObjectMapper level.

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
