### ISSUE TITLE
Unable to perform DB updates using Builder when an ObjectMapper is provided

### ISSUE THREAD

**Issue by almeidap** [vznet/mongo-jackson-mapper#9]
When providing an `ObjectMapper` to `JacksonDBCollection`, database updates through Builder queries are not performed.

Here is a simple test case:

```
public class BuilderTest {

    public static void main(String[] args) throws UnknownHostException, MongoException {
        BuilderTest tests = new BuilderTest();
        tests.testDBQuery();
    }

    private final Mongo mongo;
    private final DB db;
    private DBCollection propertyCollection;

    private ObjectMapper mapper;

    private JacksonDBCollection<Property, String> jacksonCollection;

    public BuilderTest() throws UnknownHostException, MongoException {
        mongo = new Mongo("127.0.0.1", 27017);
        db = mongo.getDB("tests");
        propertyCollection = db.createCollection("Property", null);

        mapper = new ObjectMapper();

        // Remove "mapper" parameter from 'wrap' method to make it work:
        jacksonCollection = JacksonDBCollection.wrap(propertyCollection, Property.class, String.class, mapper);
    }

    private void testDBQuery() {
        Property property = new Property();
        property.setKey("foo");

        Property saved = jacksonCollection.save(property).getSavedObject();
        System.out.println("Saved ID: " + saved.getId());

        jacksonCollection.updateById(saved.getId(), DBUpdate.set("value", "bar"));

        Property updated = jacksonCollection.findOneById(saved.getId());
        System.out.println("Value: " + updated.getValue()); // Throws NullPointerException if an ObjectMapper is provided 
    }
}
```

And the `Property` POJO:

```
public class Property {
    private String id;

    private String key;
    private String value;

    @ObjectId
    @JsonProperty("_id")
    public String getId() {
        return id;
    }

    @ObjectId
    @JsonProperty("_id")
    public void setId(String id) {
        this.id = id;
    }

    /* Other getters/setters omitted */
}
```

Maven dependencies:

<dependencies>
<dependency>
<groupId>org.mongodb</groupId>
<artifactId>mongo-java-driver</artifactId>
<version>2.7.3</version>
</dependency>
<dependency>
<groupId>net.vz.mongodb.jackson</groupId>
<artifactId>mongo-jackson-mapper</artifactId>
<version>1.4.0</version>
</dependency>
<dependency>
<groupId>org.codehaus.jackson</groupId>
<artifactId>jackson-mapper-asl</artifactId>
<version>1.9.4</version>
</dependency>
</dependencies>

**Comment by domguinard** [comment]
I actually faced the same problem. A fix would be awesome if you have any idea...

**Comment by jroper** [comment]
Sorry for not answering this sooner.  The problem is that the mongo jackson mapper requires a bit of custom configuration to be added to the object mapper.  It doesn't add this automatically when you supply your own, because it doesn't want to assume that it can just modify the custom object mapper, and if the same object mapper was passed to the wrap() method twice, this would cause issues.  I had thought that I had documented this clearly, but I just checked and there's no documentation in the javadocs whatsoever.  So I've added the documentation, and I've also provided a convenience method to do the configuration.  I've cut release 1.4.1 with these changes in it, which should be synced to maven central in a few hours.  Once you've upgraded to 1.4.1, before passing the object mapper into the wrap() method, you should pass it to MongoJacksonMapperModule.configure().

**Comment by jroper** [comment]
Also, once this configuration is added to the object mapper, then you can use the @Id annotation, instead of @JsonProperty("_id"), which you may find more convenient.
